on:
  pull_request:
    branches:
      - main

jobs:
  build_game:
    runs-on: ubuntu-latest
    name: Build and Test Game
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Build Game
      uses: firebelley/godot-export@v5.2.1
      id: export
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./game/
        cache: true
        archive_output: false
        relative_export_path: ./game/export

    - name: Debug
      run: ls -laR ${BUILD_DIR}
      env:
        BUILD_DIR: ${{ steps.export.outputs.build_directory }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: game
        path: |
          ${{ steps.export.outputs.build_directory }}/linux/
          ${{ steps.export.outputs.build_directory }}/win/
