on: 
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Export Game
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297  # 1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Update version in override.cfg
      run: sed -i "s/${VERSION_PLACEHOLDER}/${NEW_TAG}/g" ${UPDATE_FILE}
      env:
        NEW_TAG: ${{ steps.tag.outputs.new_tag }}
        VERSION_PLACEHOLDER: __placeholder_version__
        UPDATE_FILE: ./game/project.godot

    - name: Build
      id: export
      uses: firebelley/godot-export@29965918cc35b77c465839035775e0e12dc87029  # v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
        relative_project_path: ./game/
        cache: true
        archive_output: false
        use_preset_export_path: true

    - name: Bundle Head Script
      run: |
        cp ./game/builds/web/enable-threads.js ${BUILD_DIR}/web/
      env:
        BUILD_DIR: ${{ steps.export.outputs.build_directory }}

    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b  # v5.0.0

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa  # v3.0.1
      with:
        path: ${{ steps.export.outputs.build_directory }}/web

    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: game
        path: |
          ${{ steps.export.outputs.build_directory }}/linux/
          ${{ steps.export.outputs.build_directory }}/win/

  deploy:
    needs: build
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4.0.5

      - name: Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: game

      - name: Create Zips
        run: |
          zip -r linux.zip linux
          zip -r win.zip win

      - name: create release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174  # v1.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ needs.build.outputs.tag }}
          artifacts: linux.zip,win.zip
