on: 
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Export Game
      id: export
      uses: firebelley/godot-export@v5
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./game/
        cache: true
        archive_output: true
        relative_export_path: ./game/export

    - name: create release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ steps.tag.outputs.new_tag }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
